### ISSUE TITLE
[FEATURE REQUEST] - Use midi files as midi in

### ISSUE THREAD

**Issue by maditnerd** [josephernest/SamplerBox#15]
Simon posted yesterday, 21:46:
http://www.samplerbox.org/forum/141

Is there a way to use a midi file as input ?

I was so entrained by this project that i bougth everything and assabled it without even thinking about the need of a midi device to give the box some input.
In about three weeks i'll have plenty midi devices to play with but i dont want to wait :)

Thanks in advance!

**Comment by josephernest** [comment]
Hi @maditnerd, I close this one, there is probably some Linux tool that can take a MIDI file as input and output notes in realtime to any MIDI device. The solution would be to use a "virtual MIDI device" between SamplerBox and this tool (In Windows there are also virtual MIDI devices like [LoopBe1](https://nerds.de/en/loopbe1.html), I don't know the name for such tool on Linux though).
