### ISSUE TITLE
Raspberry Pi 3 - Image doesn't works

### ISSUE THREAD

**Issue by maditnerd** [josephernest/SamplerBox#18]
Dorgangrinder posted Mar 24, 13:11:
http://www.samplerbox.org/forum/133

# Martin posted Apr 7, 19:47:
Hey all, further to my original post I decided to give it a shot myself. I can confirm the image doesn't work on rpi3, but installing it manually does.
There are various changes you'll need to make to the samplerbox.py in order to get it working though. 

* For example, the /media mount isn't automatically created
* the display() function is referencing a dependency that doesn't exist (though I did install all dependencies stated in the git repo) and the 
* samplerbox obviously won't automatically start.

If anyone wants more info, please let me know.

# Jerome posted Apr 16, 12:02:

* boot-delay passed from 0 to 1 (config.txt) => no change

* replaced the kernel image with a recent one directly in boot partition => no change

* I replace also the file star.elf in the boot partition : booting !

But, I am always stuck without any sound produced due to some configuration error...

**Comment by josephernest** [comment]
Solved with http://samplerbox.org/forum/176
