### ISSUE TITLE
New Feature: jack support

### ISSUE THREAD

**Issue by stef35** [josephernest/SamplerBox#28]
A great thing for amplerbox would be to add jack support.

This feature would open easy integration with any other jack supported applications, for instance, sooperlooper (to make some live loops)

An API exists: http://www.jackaudio.org/api/

Bravo for this project that definitely rocks ;-)

**Comment by josephernest** [comment]
Thanks @stef35, sorry for the massive delay :) I want to keep the project as light as possible, with the least number of external dependencies, so Jack is not included out-of-the-box, but it's definitely a cool idea to use it if you need more advanced features.
