### ISSUE TITLE
Support for mp3, flac, ogg, etc?

### ISSUE THREAD

**Issue by naught101** [josephernest/SamplerBox#31]
Some of the sample files available for some of the better patches take up a lot of memory. How hard would it be to add support for ogg, flac, and/or mp3?

**Comment by josephernest** [comment]
I like the idea, but it would eat a lot of CPU to decode MP3 in realtime. This would probably make the polyphony much lower on a RPi. I'm not sure, but it could be the same for lossless compression (it's fast on a desktop computer, but on a Pi, I don't know).

Also, MP3 doesn't seem to support `loop markers` (I just tried to add a sustaining loop with Sound Forge on a MP3 file, then after saving, the loop is gone) or similar metadata which are useful for samplers.

Still, it could be interesting to test it. Feel free to experiment on this and post your solution, we'll look at it.
