### ISSUE TITLE
little app to add sample markers to your wave files

### ISSUE THREAD

**Issue by fjgaston** [josephernest/SamplerBox#41]
Hi,
As I was strugling to add sample marker to my wave files, and I don't want to buy sound forge only for this I wrote this little code to add sample marker to a wave file.
It's very basic but it can be useful.
I'm new to github so I don't know if I should pull it or something so here is the code :

`######## ---- samplemarker.py ----
#### Florent Jean Gaston

import struct
import binascii

print "welcome here buddy"
print "##################"
print "so you want to add sampler markers to a wave file ?"
print ""
print ""

my_file = raw_input("What's the name of your file ?")
print my_file

with open(my_file, 'rb+') as f:
    #for i in range (4, 7) :
    f.seek(4)
    data = f.read(4)
    data = struct.unpack("<L",data)
    data = int(data[0])
    print "Your file : "+my_file
    print "File size : "+str(data)+" bytes"
    
    print " "
    start_loop = input("First sample of the loop ? ")
    
    end_loop = input("Last sample of the loop ? ")
    
    sure = raw_input("Are you really sure that you want to proceed (y/n) ? ") 
    if sure == "n":
        print "abord mission ..."
        quit()
    else:
        print "proceeding ..."
        
    
    data = data+68 #ajoute 68 bytes au fichier
    
    #print data
    
    data = struct.pack("<L",data)
    #print data
    f.seek(4)
    f.write(data)
    f.close
    
  
    
with open(my_file, 'a+') as f:
    
    smplmarker = '736D706C3C0000000000000000000000000000003C00000000000000000000000000000001000000000000000000000000000000'
    smplmarker = binascii.unhexlify(smplmarker)
    #print smplmarker
    f.write(smplmarker)
    start_loop = struct.pack("<L",start_loop)
    f.write(start_loop)
    end_loop = struct.pack("<L",end_loop)
    f.write(end_loop)
    endmarker = '0000000000000300'
    endmarker = binascii.unhexlify(endmarker)
    f.write(endmarker)
    f.close
print 'Done !!!'    

    `

**Comment by josephernest** [comment]
Nice one, cool that you found this working solution!

I did similar additions to Python's `wave.py` module and scipy's `wavefile.py` to support markers. If interested, see https://afewthingz.com/pythonaudiomodules
