### ISSUE TITLE
Error in the install guide

### ISSUE THREAD

**Issue by shawnpinciara** [josephernest/SamplerBox#59]
It's written to install the python package 
- rtmidi-python
Which it's known having issues (https://stackoverflow.com/questions/70979605/unknown-error-when-installing-python-rtmidi)
so instead it should be written:
- python-rtmidi
which is the valid rtmidi package

**Comment by theredled** [comment]
No, as discussed here https://github.com/josephernest/SamplerBox/issues/58, Samplerbox is not currently compatible with python-rtmidi and Python 3.9+.
Maybe you could try my Python 3.9-compatible fork, although not fully tested everywhere nor playing loops: https://github.com/theredled/SamplerBox

**Comment by josephernest** [comment]
Thanks @shawnpinciara @theredled for the report. 

rtmidi-python works with Python 3.9+ (without any modification in the code), I'll update the installation instructions soon, see https://github.com/superquadratic/rtmidi-python/issues/25.
