### ISSUE TITLE
150ms latency: normal?

### ISSUE THREAD

**Issue by theredled** [josephernest/SamplerBox#60]
Hi, I'm using original soundcard with RPi 3 model B.
I have a huge ~150 ms latency, is it something expected with Samplerbox and my modest configuration?
Or is there something wrong on my side?
Thanks a lot

**Comment by josephernest** [comment]
Hi Benoît
No this not normal, the latency should be around 15 or 20 ms.

**Comment by theredled** [comment]
Follow-up, it was `pulseaudio` taking a lot of memory. No details, removing it solved the problem.
