### ISSUE TITLE
Raspberry PI 5

### ISSUE THREAD

**Issue by janjakabovic** [josephernest/SamplerBox#61]
Is new raspberry PI supported? Thanks.

**Comment by josephernest** [comment]
@janjakabovic I don't have a Pi5 to test now. If you do, can you try the ready-to-use image and post the results? Thanks!

In any case, [this method](https://github.com/josephernest/SamplerBox?tab=readme-ov-file#install) will always work, no matter the Pi version (as long as Python is supported ;)).
