### ISSUE TITLE
Crackling (also with external sound card)

### ISSUE THREAD

**Issue by ephemer** [josephernest/SamplerBox#9]
My Raspberry Pi 2 B arrived yesterday, which I bought with the intention of using SamplerBox with it. I loaded a bunch of samples on it and was really stoked to hear the sounds coming out of a tiny computer running a python script! I commend you on your awesome work so far!

The issue: I found that playing three of more samples at once often results in a hard crackling sound that sounds like clipping. This makes it pretty much to play the sampler like a piano as I'm planning to (I have a Nord synth without piano sounds that I'm hoping to supplement with the SamplerBox).

I am using a cheap mini USB audio interface. I don't think it's quite as high-quality as the DAC you recommend, but I have used it for DJing with Traktor in the past without issue, so I don't think it's that.

I'm assuming this really is clipping. Any ideas how we can prevent this, presumably with a compressor / limiter setup? I will test this over the weekend by turning down the master volume. This isn't really a long-term solution though (it should be able to keep up with the Nord volume level to at least a reasonable degree).

I found a basic limiter written in C with Python bindings but beyond that there seems to be amazingly little available in the open source community. Am I missing something, I mean is this built into ALSA or JACK or something and I just don't know about it?

**Comment by josephernest** [comment]
Two ideas:

* Use the recommended USB DAC (the cheap 6€ one, using Texas Instrument PCM2704 chipset which is excellent). This solved the problem for 90% of people sending me emails "The sound is distorded / cracking / etc."

* Permanently turn down the volume, [as shown here](http://samplerbox.org/faq#volume).
